name:                bt-json
version:             0.1.0.0
github:              "angelbeltran/bt-json"
license:             BSD3
author:              "Angel Beltran"
maintainer:          "me@angelbeltran.com"
copyright:           "2019 Angel Beltran"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/angelbeltran/bt-json#readme>

dependencies:
- base >= 4.7 && < 5
- streamly >= 0.7
- bytestring >= 0.11
- aeson >= 0.6
  #- bytestring >= 0.10
  #- word8 >= 0.1.3

library:
  source-dirs: src

executables:
  bt-json-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bt-json

tests:
  bt-json-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bt-json
